export const PRODUCT = [
            {   
                "id":1,
                "name": "Máy ảnh Sony A6000",
                "category": "Máy ảnh",
                "description": "Máy ảnh Sony Alpha A6000 chiếc máy ảnh Mirrorless là sự cải tiến vượt bậc của Sony với khoảng thời gian lấy nét chỉ trong 0.06s. Ngoài ra,những hình ảnh với dải màu sâu và độ tương phản mềm mại sẽ được tạo ra liên tục với hơn 600 tấm ảnh chỉ trong một lần sạc pin.Máy được trang bị bộ cảm biến Exmor APS HD CMOS 24.3MP APS-C và bộ xử lý hình ảnh BIONZ X có độ phân giải cao rất có lợi để chụp những ảnh khổ lớn chuyên dụng cho thiết kế hay những chi tiết dù nhỏ nhất cũng sẽ được ghi lại qua từng điểm ảnh một các rõ nét nhất.",
                "price": 8000000,
                "percentSale": 1,
                "img": null,
                "quantity": 30,
                "status": 1,
                "deletedAt": null
            },
            {   
                "id":2,
                "name": "Máy ảnh Sony A6300",
                "category": "Máy ảnh",
                "description": "Máy ảnh không gương lật A6000 đã được hãng công nghệ Nhật thay thế bằng máy ảnh Sony A6300. Dù ngoại hình không đổi nhưng những cải tiến bên trong mới là thứ đáng giá với khả năng lấy nét nhanh nhất thế giới.Hệ thống lấy nét của máy ảnh Sony này được cải tiến với 425 điểm lấy nét AF theo pha, tích hợp hệ thống tự động kích hoạt các điểm AF xung quanh một chủ thể. Sony cho biết A6300 có hệ thống lấy nét được gọi là 4D FOCUS™ tốc độ lấy nét nhanh nhất thế giới là 0.05 giây. khi lấy nét, máy tự động kích hoạt một hệ thống theo dõi các điểm khác nằm ngoài vùng nét của vật thể, nếu có sự dịch chuyển của vật thể thì hệ thống sẽ tuỳ chỉnh lấy nét ngay lập tức, mật độ điểm nét kiểu dự phòng này nhiều gấp 7.5 lần so với phiên bản Sony A6000.",
                "price": 12000000,
                "percentSale": 1,
                "img": null,
                "quantity": 30,
                "status": 1,
                "deletedAt": null
            },
            {   
                "id":3,
                "name": "Máy ảnh Sony A6400",
                "category": "Máy ảnh",
                "description": "Mới đây hãng Sony đã cho ra mắt chiếc máy ảnh mirroless mới nhất của họ là A6400. Chiếc máy ảnh này sở hữu nhiều tính năng và thông số cực kì ấn tượng, bao gồm lấy nét theo mắt và theo dõi thời gian thực cùng hệ thống tự động lấy nét nhanh nhất thế giới. Mẫu máy ảnh mirroless nhỏ gọn hướng trực tiếp đến đối tượng người dùng nhiếp ảnh du lịch, sáng tạo nội dung và vlogger.Máy ảnh Sony A6400 (Bạc) được trang bị cảm biến hình ảnh APS-C Exmor CMOS 24.2MP và kết hợp với bộ xử lý BIONZ X nâng cấp nhằm mang lại chất lượng hình ảnh cũng như cải thiện tái tạo màu sắc trong mọi điều kiện chụp.",
                "price": 18000000,
                "percentSale": 1,
                "img": null,
                "quantity": 30,
                "status": 1,
                "deletedAt": null
            },
            {   
                "id":4,
                "name": "Máy ảnh Sony A6500",
                "category": "Máy ảnh",
                "description": "Máy ảnh Sony A6500 là một chiếc máy ảnh miroless dùng cảm biến APS-C có độ phân giải 24MP rất phù hợp cho cả việc chụp ảnh và quay phim. Với những tính năng cao cấp của hãng Sony được trang bị vào một thân hình nhỏ gọn mang đến những hiệu suất làm việc tuyệt vời sẽ là lựa chọn tuyệt vời cho những hoạt động hàng ngày của bạn.Máy ảnh Sony A6500 là chiếc máy ảnh Mirrorless được trang bị bộ cảm biến 24.2MP Exmor CMOS và bộ xử lý hình ảnh BIONZ X cho chất lượng hình ảnh sạch sẽ được cung cấp với một phạm vi độ nhạy mở rộng rộng tiêu chuẩn ISO 51200, cùng với tốc độ readout tăng tốc cho các nội 4K30 và Full HD 1080p120 quay video với readout full pixel. ",
                "price": 15000000,
                "percentSale": 1,
                "img": null,
                "quantity": 30,
                "status": 1,
                "deletedAt": null
            },
            {   
                "id":5,
                "name": "Máy ảnh Sony A7 Mark 2",
                "category": "Máy ảnh",
                "description": "Máy sở hữu bộ cảm biến Exmor CMOS full-frame với số điểm ảnh hiệu dụng là 24.3 MP nên chất lượng ảnh là tốt nhất với những ai muốn in ảnh khổ lớn. Ngoài ra, fullframe 117 điểm là sức mạnh đưa lại sự sắc nét cho các chi tiết trong từng điểm ảnh.Ngoài ra, Sony Alpha A7 M2 còn được cải thiện đến 30% tốc độ bắt nét và 50% tốc độ tracking. Đây chính là ưu thế vượt trội của A7M2 với những ai chuyên chụp thể loại chuyển động nhanh.Nhưng nổi bật nhất của sự cải tiến chính là công nghệ chống rung 5 trục hoàn toàn mới trên thân máy. Công nghệ này đem lại cho người dùng khả năng bù tối đa 4 đến 5-stops, hỗ trợ việc chụp ảnh “cầm tay” ở tốc độ thấp. Khi bấm nửa nút chụp ảnh và kích hoạt chống rung SteadyShot, cảm biến sẽ rung lắc khi người dùng dịch chuyển máy ảnh.",
                "price": 14000000,
                "percentSale": 1,
                "img": null,
                "quantity": 30,
                "status": 1,
                "deletedAt": null
            },
            {   
                "id":6,
                "name": "Máy ảnh Sony A7 Mark 3",
                "category": "Máy ảnh",
                "description":"Sony đã trang bị cho sản phẩm mới nhất của mình cảm biến 24MP mới hoàn toàn với bộ xử lý ảnh BIONZ X quen thuộc. Bên cạnh đó, thêm một chip ngoại vi front-end LSI tăng khả năng đọc/ghi dữ liệu lớn. Việc khử nhiễu được đảm nhận bởi dải ISO rộng 100 – 51.200 và còn có thể mở rộng lên tới 204.800. Vì thế, ở cả môi trường đủ sáng và thiếu sáng việc chụp ảnh không còn khiến bạn phải lo lắng về vấn đề nhiễu hạt.Chiếc máy ảnh Sony A7 Mark III này cũng đã làm thay đổi quan niệm về việc mirrorless lấy nét chậm khi được trang bị một hệ thống lấy nét khá là bá đạo. Nếu chiếc A7R Mark III ra mắt cuối năm 2017 với 399 điểm thì A7 Mark III lại có tới 693 điểm theo pha bao phủ toàn bộ khung hình. Trong đó, có tới 425 điểm lấy nét tương phản đi kèm chế độ 4D Focus khiến cho các đối tượng di chuyển cực nhanh cũng bị khóa nét dễ dàng. Như vậy là nếu những ai không đủ khả năng sắm A9 để chụp thể thao vẫn có thể dùng máy này như một sự thay thế ở mức chấp nhận được.",
                "price": 32000000,
                "percentSale": 1,
                "img": null,
                "quantity": 30,
                "status": 1,
                "deletedAt": null
            },
            {   
                "id":7,
                "name": "FE 85mm F1.8",
                "category": "Ống kính",
                "description":" Lợi ích thiết kế quang học là một cách bố trí vật lý đơn giản, trực quan kết hợp nút giữ lấy nét có thể tùy chỉnh và chuyển đổi vật lý AF / MF. Động cơ hai trục AF tự động đạt được hiệu suất tập trung nhanh, yên tĩnh, và động cơ này cũng cung cấp hiệu suất lấy nét bằng tay nhanh để điều khiển tinh chỉnh. Thiết kế gọn nhẹ (371g, 13,1 oz.) cực kỳ phù hợp với các dòng máy ảnh Sony α7 mang đến sự pha trộn hoàn hảo giữa tính di động và chất lượng hình ảnh cao khi chụp chân dung, sự kiện và nhiều hơn nữa.Khẩ độ tối đa F1.8 mang lại lợi ích cho việc sử dụng ống kính trong điều kiện ánh sáng yếu và cũng có thể kiểm soát sâu rộng độ sâu trường khi làm việc với các kỹ thuật lấy nét có chọn lọc.Độ sắc nét và hiệu ứng bokeh mượt mà không gì sánh được của ống kính chụp tele tầm trung vượt trội được thiết kế tỉ mỉ cho chụp chân dung và ống kính Sony này chính là lựa chọn xuất sắc.",
                "price": 10000000,
                "percentSale": 1,
                "img": null,
                "quantity": 30,
                "status": 1,
                "deletedAt": null
            },
            {   
                "id":8,
                "name": "FE 50mm F1.8",
                "category": "Ống kính",
                "description":"Sony FE 50mm f/1.8 là một ống kính được thiết kế cho dòng máy ảnh full-frame E-mount, mang đến sự đơn giản, nhỏ gọn với trọng lượng chỉ 186 gram. Đây là một ống kính rất chắc chắn, kiểu dáng đẹp, thanh thoát, khẩu độ lớn f/1.8 và khả năng kiểm soát lấy nét tốt. Nó rất phù hợp cho bạn khi sử dụng chụp ảnh hàng ngày.",
                "price": 4000000,
                "percentSale": 1,
                "img": null,
                "quantity": 30,
                "status": 1,
                "deletedAt": null
            },
            {   
                "id":9,
                "name": "FE 55mm Cz F1.8",
                "category": "Ống kính",
                "description":"Ống kính Sony Sonnar T * FE 55mm f / 1.8 ZA là ống kính được đánh giá “ngon - bổ - rẻ” nhất trong tất cả các ống kính phục vụ cho dòng máy ảnh A7. Với chất lượng quang học tuyệt vời mang đến cho bạn những trải nghiệm thú vị với những hình ảnh có độ sắc nét cao, tương phản tốt và màu sắc vô cùng chân thật.Độ tương phản và độ phân giải ZEISS danh tiếng tận dụng tối đa điểm mạnh của cảm biến hình ảnh full frame như ảnh ở sê-ri Sony α7 và khẩu độ tối đa F1.8 có thể cho ra hiệu ứng bokeh hình nền full-frame tuyệt đẹp.Ống kính Sony Sonnar T * FE 55mm f / 1.8 ZA với khẩu độ tròn 9 lá khẩu kết hợp với quang học hàng đầu của ống kính giúp tạo ra hiệu ứng bokeh mượt mà tuyệt đẹp ở các vùng nền ngoài khu vực lấy nét như mong muốn, với ánh sáng tự nhiên không làm rối chủ thể và các chi tiết quan trọng phía trước.",
                "price": 32000000,
                "percentSale": 1,
                "img": null,
                "quantity": 30,
                "status": 1,
                "deletedAt": null
            },
            {   
                "id":10,
                "name": "SEL 50mm F1.8",
                "category": "Ống kính",
                "description":"Ống kính Sony SEL 50mm F1.8 là ống kính fix được sản xuất dành riêng cho các máy ảnh Sony không gương lật sử dụng cảm biến APS-C, nơi mà nó cung cấp một tiêu cự 75mm tương đương trên cảm biến fullframe.Ống kính có thiết kế nhẹ và nhỏ gọn với thân ống kính được làm bằng hợp kim nhôm cao cấp được khắc vòng tập trung cho khả năng cầm nắm chắc tay và dể dàng thao tác.Ống kính này được cấu tạo bao gồm 9 yếu tố chia thành 8 nhóm với thiết kế quang học tiên tiến để đạt được rõ ràng, hình ảnh chất lượng cao bằng cách giảm thiểu hiệu quả biến dạng và quang sai màu.",
                "price": 4000000,
                "percentSale": 1,
                "img": null,
                "quantity": 30,
                "status": 1,
                "deletedAt": null
            },
            {   
                "id":11,
                "name": "Máy ảnh Sony ZV-1",
                "category": "Máy ảnh",
                "description":"Máy ảnh được trang bị một ống kính zoom tiêu chuẩn thương hiệu ZEISS có tiêu cự tương đương 24-70mm ấn tượng, với phạm vi khẩu độ tối đa f/1.8-2.8, đi kèm với đó là tính năng ổn định hình ảnh Active SteadyShot giúp ổn định cảnh quay và giảm rung máy giúp các cảnh quay trở nên mượt mà hơn.Quay Vlog giờ đây đã trở nên cực kỳ dễ dàng với Sony ZV-1 chiếc máy ảnh compact nhỏ gọn được sinh ra để dành riêng cho các Vlogger sáng tạo nội dung video hay những người hay livestream để bán hàng, sản xuất video chơi game... Tốc độ lấy nét nhanh, Eye AF liên tục và một thiết kế nhỏ gọn để bạn có thể mang tới bất cứ nơi đâu trong chuyến đi của mình.",
                "price": 17000000,
                "percentSale": 1,
                "img": null,
                "quantity": 30,
                "status": 1,
                "deletedAt": null
            },
            {   
                "id":12,
                "name": "FE 24-70GM F2.8",
                "category": "Ống kính",
                "description":"Ống kính Sony G Master FE 24-70mm F2.8 là một trong 3 ống kính cao cấp mà Sony vừa mới cho ra mắt trong khoảng thời gian gần đây. Là một ống kính góc rộng đến tele trung bình được thiết kế dành riêng cho máy ảnh không gương lật E-mount. Ống kính được đánh giá cao khi có khả năng kết hợp cả độ sắc nét và bokeh một cách mượt mà - điều mà rất ít ống kính làm được.Mặc dù chất liệu bên ngoài làm bằng nhựa nhưng ống kính vẫn rất chất, trọng lượng 220g khá đằm tay và chắc chắn khi sử dụng. Với đường kính kính lọc 82mm được cải tiến lớn hơn, Ống kính Sony G Master FE 24-70mm F2.8 có khả năng thu sáng tốt hơn với khẩu độ f/2.8.Với một hằng số f / 2.8 khẩu độ tối đa trong suốt dải tiêu cự, ống kính này duy trì thực hiện nhất quán trong suốt dải zoom và lợi ích làm việc trong điều kiện thiếu ánh sáng và với các kỹ thuật tập trung chọn lọc. Cho phép bạn dể dàng kiểm soát độ sâu trường ảnh cũng như thỏa sức sáng tạo trong việc khống chế độ sâu trường ảnh.",
                "price": 40000000,
                "percentSale": 1,
                "img": null,
                "quantity": 30,
                "status": 1,
                "deletedAt": null
            },
];